# Project
group = dev.tophatcat.knockknock
mod_name = Knock Knock
mod_id = knockknock
credits = KiriCattus
description = Knock Knock! Who's there? Knock Knock is a small mod that gives a 'knock' sound when you punch a door! Wow!

# Links
homepage_url = https://tophatcat.dev
discord_url = https://discord.tophatcat.dev
sources_url = https://github.com/kiris-mods/knock-knock
issues_url = https://github.com/kiris-mods/knock-knock/issues
license_url = https://github.com/kiris-mods/knock-knock/blob/dev/LICENSE.md

# Common
java_version = 25
minecraft_version = 26.1.2
modrinth_id = wC6tEbQM
curseforge_id = 238842

# NeoForge
# See https://projects.neoforged.net/ for new versions
# See https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
neoforge_version = 26.1.2.59-beta
neo_form_version = 26.1.2-1

moddevgradle_version = 2.0.141

# Fabric
# See https://fabricmc.net/develop/ for new versions
fabric_loom = 1.16.2
fabric_version = 0.149.0
fabric_loader_version = 0.19.2

# Dependencies
# - Common

# - NeoForge

# -- Optional
jade_neoforge_version = 26.1.1

# - Fabric

# -- Optional
jade_fabric_version = 26.1.0
modmenu_version = 18.0.0-beta.1

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.debug = false
org.gradle.configuration-cache = false
org.gradle.caching = true
org.gradle.parallel = true
