# Gradle
org.gradle.jvmargs=-Xmx2G
# Enable Gradle build cache
org.gradle.caching=true
# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Project metadata
group=dev.tophatcat.knockknock
mod_id=knockknock
mod_description=Knock Knock! Who's there? Knock Knock is a small mod that gives a 'knock' sound when you punch a door! Wow!
mod_display_name=KnockKnock
sources_url=https://github.com/kiris-mods/knock-knock
issues_url=https://github.com/kiris-mods/knock-knock/issues
license_url=https://github.com/kiris-mods/knock-knock/blob/dev/LICENSE.md
discord_url=https://discord.tophatcat.dev
homepage_url=https://tophatcat.dev/mods/minecraft/#knock-knock

curseforge_id=238842
modrinth_id=wC6tEbQM
